### ISSUE TITLE
Problem in Mouse wheel

### ISSUE THREAD

**Issue by Bh-Navraj** [yCodeTech/horizontal-timeline-2.0#22]
**Describe the bug**
After enabling mouse wheel option and when we scroll the mouse the timeline directly go to the end of the timeline date. It should be scroll smothly each timeine one by one.

**Comment by yCodeTech** [comment]
Thanks for using Horizontal Timeline 2.0!

The way it works is that it will be scrolled according to how much force or acceleration the wheel has. So if the mouse wheel is scrolled with quite a bit of force/acceleration then the timeline will scroll multiple events at once. But if a tiny push on the wheel, the timeline scrolls 1 event. It all depends on how many "notches" the wheel scrolls to how much the timeline is scrolled.

If still doesn't work after trying a slower wheel scroll, please create a minimal replicate of the issue via codepen or similar, and I will look in to it.

**Comment by Bh-Navraj** [comment]
Is it possible to wheel the content one by one, so that force or acceleration  of the wheel does not effet the content?

**Comment by yCodeTech** [comment]
It's not currently possible. The 3rd party plugin Mousewheel that is used calculates all the stuff, and all the timeline does is checks if the wheel was scrolled back or forward to determine the direction of scrolling (prev or next). The documentation of the mousewheel plugin is very limited as is the customisation.

However, there is nothing stopping you from coding a makeshift function outside of the plugin, and you can just utilise the timeline's Go To Event method. With a bit of jQuery magic I'm sure you'll be able to get the prev or next event and use it's date in the data attribute for the method to work.

If you would like to help improve this plugin and you know how to solve this issue, by all means create a pull request with the new code, it would be muchly appreciated.

Thanks again for using Horizontal Timeline 2.0!

**Comment by Bh-Navraj** [comment]
Thank You !!
