### ISSUE TITLE
JSON Data Array and Callbacks

### ISSUE THREAD

**Issue by databind10** [yCodeTech/horizontal-timeline-2.0#23]
I have integrated this timeline into one of my hobby projects and these are the issues and features I have integrated:

1.  **Issue**: This style interferes with other code that allows a div to follow you when you scroll the page. html, body { overflow-x: hidden; }. I fixed this by removing the style and adding the following to _updateVisibleContent. Added `$('html, body').css('overflow-x', 'hidden');` to the top, and `$('html, body').css('overflow-x', 'auto');` to the end of the function. 

2. **Callback feature**. I wanted to perform additional updates after the timeline has successfully scrolled to the new event. I added a new property to the settings JSON config called callback. At the end of _updateVisibleContent, I added `if (this.settings.callback !== '') this.settings.callback(json);` I track down the JSON and pass it to the callback. Here is that code in a nutshell without all of the null checks: `JSON.parse(eventsContent[0].querySelector('li.selected').getAttribute('data-horizontal-timeline')): `

3. ) It would be great if there was a **data property** in the config where I can just pass in a **JSON array of all the timeline events**. This way, I don't have to build the ordered list for each item that needs a timeline view. I'll probably extend the code to do this for me at a later time.

**Comment by yCodeTech** [comment]
Hi, firstly thanks for using Horizontal Timeline 2.0!
I don't currently have time to work on this project, but by all means you can fork this repo and add the new code, and submit a pull request to this repo. I can then merge it once tests have been done.
