### ISSUE TITLE
onChangeListener

### ISSUE THREAD

**Issue by Jingo91** [yCodeTech/horizontal-timeline-2.0#4]
Is there any listener, which fires, when autoplay changes to next date or the user clicks on a date?
Would be nice to know, which date is currently selected.

**Comment by yCodeTech** [comment]
Hi, thanks for contacting me via email and opening an issue. 

I can confirm that there are no internal events to listen for. However, after considering how useful this could be, I have decided to add it to the plugin as `eventChanged` along with 2 others (`eventAdded` and `eventRemoved`) and will be available in the next version, which should be very soon.

Please look out for the next version. I will respond to your email as soon as I release it with additional info.

If there are any other improvements or feature requests that I should consider, please don't hesitate to do so.
